language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
    allow_failures:
        - php: hhvm
    include:
        - php: 5.5
          env: dependencies=lowest
        - php: 5.6
          env: dependencies=lowest
        - php: 7
          env: dependencies=lowest

before_install:
  - composer self-update

install:
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable --prefer-source --no-interaction; else composer install --prefer-source --no-interaction; fi;

script: ./vendor/bin/phpunit --coverage-text
