language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

env:
  - SYMFONY_VERSION="2.2.0"
  - SYMFONY_VERSION="~2.2"

before_install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update --no-interaction
  - composer require symfony/security-bundle:${SYMFONY_VERSION} --no-update --no-interaction

install:
  - composer install --dev --prefer-source --no-interaction

script: ./vendor/bin/phpunit --coverage-text
